"""empty message

Revision ID: 180e22dccfc4
Revises: 47332773e1c2
Create Date: 2019-09-10 23:29:17.536316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180e22dccfc4'
down_revision = '47332773e1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dip_diploma', sa.Column('project_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dip_diploma', 'project_content')
    # ### end Alembic commands ###
