"""empty message

Revision ID: 47332773e1c2
Revises: 
Create Date: 2019-09-10 23:08:09.643039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47332773e1c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dip_diploma',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('compete_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('diploma_time', sa.Date(), nullable=True),
    sa.Column('level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('rank', sa.VARCHAR(length=20), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dip_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diploma_id', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diploma_id'], ['dip_diploma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dip_member')
    op.drop_table('dip_diploma')
    # ### end Alembic commands ###
