"""empty message

Revision ID: c9ba518da4ea
Revises: ce2b1257f836
Create Date: 2019-09-11 14:03:35.088082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9ba518da4ea'
down_revision = 'ce2b1257f836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dip_teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diploma_id', sa.Integer(), nullable=True),
    sa.Column('teacher_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diploma_id'], ['dip_diploma.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('dip_member', 'diploma_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dip_member', 'diploma_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_table('dip_teacher')
    # ### end Alembic commands ###
