"""empty message

Revision ID: ce2b1257f836
Revises: 180e22dccfc4
Create Date: 2019-09-10 23:55:32.133151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2b1257f836'
down_revision = '180e22dccfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dip_diploma', sa.Column('image_path', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dip_diploma', 'image_path')
    # ### end Alembic commands ###
